var myString;
var myNum;
var myBool;
var myVar;
myString = "Hello world";
myNum = 22;
myBool = true;
myVar = "hello";
var strArr;
var numArr;
var boolArr;
strArr = ["hello", "world"];
numArr = [1, 2, 3];
boolArr = [true, false, true];
var strArrAlt;
var numArrAlt;
var boolArrAlt;
strArrAlt = ["hello", "world"];
numArrAlt = [1, 2, 3];
boolArrAlt = [true, false, true];
var strNumTuple;
var myVoid = null;
var myNull = null;
var myUndefined = undefined;
strNumTuple = ["Hello", 4];
console.log(myUndefined);
